// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestOMatic.Web.Infrastructure.Persistence;

#nullable disable

namespace RestOMatic.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005172939_AddHosts")]
    partial class AddHosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RestOMatic.Web.Features.Accounts.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("PasswordCredentials", (string)null);
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Accounts.ProfilePicture", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("UserId");

                    b.ToTable("ProfilePictures", (string)null);
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Accounts.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPicture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PictureVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Hosts.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arch")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CredentialHash")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("EnrolTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EnrolTokenHash")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("EnrolledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCheckInAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("RestOMaticVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResticVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialHash")
                        .IsUnique();

                    b.HasIndex("EnrolTokenHash")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Hosts", (string)null);
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Hosts.HostPart", b =>
                {
                    b.Property<Guid>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WithheldFields")
                        .HasColumnType("TEXT");

                    b.Property<string>("WithheldReason")
                        .HasColumnType("TEXT");

                    b.HasKey("HostId", "Kind");

                    b.ToTable("HostParts", (string)null);
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Accounts.PasswordCredential", b =>
                {
                    b.HasOne("RestOMatic.Web.Features.Accounts.User", null)
                        .WithOne("Password")
                        .HasForeignKey("RestOMatic.Web.Features.Accounts.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Accounts.ProfilePicture", b =>
                {
                    b.HasOne("RestOMatic.Web.Features.Accounts.User", null)
                        .WithOne("Picture")
                        .HasForeignKey("RestOMatic.Web.Features.Accounts.ProfilePicture", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Hosts.HostPart", b =>
                {
                    b.HasOne("RestOMatic.Web.Features.Hosts.Host", null)
                        .WithMany("Parts")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Accounts.User", b =>
                {
                    b.Navigation("Password");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("RestOMatic.Web.Features.Hosts.Host", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
